// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/dubovayaRoshcha/posts-service/internal/entity"
	dto "github.com/dubovayaRoshcha/posts-service/internal/usecase/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockPostUseCase is a mock of PostUseCase interface.
type MockPostUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostUseCaseMockRecorder
}

// MockPostUseCaseMockRecorder is the mock recorder for MockPostUseCase.
type MockPostUseCaseMockRecorder struct {
	mock *MockPostUseCase
}

// NewMockPostUseCase creates a new mock instance.
func NewMockPostUseCase(ctrl *gomock.Controller) *MockPostUseCase {
	mock := &MockPostUseCase{ctrl: ctrl}
	mock.recorder = &MockPostUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostUseCase) EXPECT() *MockPostUseCaseMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostUseCase) CreatePost(ctx context.Context, post dto.PostDTO) (*entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, post)
	ret0, _ := ret[0].(*entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostUseCaseMockRecorder) CreatePost(ctx, post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostUseCase)(nil).CreatePost), ctx, post)
}

// GetListPosts mocks base method.
func (m *MockPostUseCase) GetListPosts(ctx context.Context, params dto.PostRequest) (*dto.PostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListPosts", ctx, params)
	ret0, _ := ret[0].(*dto.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListPosts indicates an expected call of GetListPosts.
func (mr *MockPostUseCaseMockRecorder) GetListPosts(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListPosts", reflect.TypeOf((*MockPostUseCase)(nil).GetListPosts), ctx, params)
}

// GetPostByID mocks base method.
func (m *MockPostUseCase) GetPostByID(ctx context.Context, postID int) (*entity.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", ctx, postID)
	ret0, _ := ret[0].(*entity.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockPostUseCaseMockRecorder) GetPostByID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockPostUseCase)(nil).GetPostByID), ctx, postID)
}

// MockCommentUseCase is a mock of CommentUseCase interface.
type MockCommentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUseCaseMockRecorder
}

// MockCommentUseCaseMockRecorder is the mock recorder for MockCommentUseCase.
type MockCommentUseCaseMockRecorder struct {
	mock *MockCommentUseCase
}

// NewMockCommentUseCase creates a new mock instance.
func NewMockCommentUseCase(ctrl *gomock.Controller) *MockCommentUseCase {
	mock := &MockCommentUseCase{ctrl: ctrl}
	mock.recorder = &MockCommentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentUseCase) EXPECT() *MockCommentUseCaseMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentUseCase) CreateComment(ctx context.Context, comment dto.CommentDTO) (*entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, comment)
	ret0, _ := ret[0].(*entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentUseCaseMockRecorder) CreateComment(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentUseCase)(nil).CreateComment), ctx, comment)
}

// GetCommentReplies mocks base method.
func (m *MockCommentUseCase) GetCommentReplies(ctx context.Context, params dto.CommentRequest) (*dto.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentReplies", ctx, params)
	ret0, _ := ret[0].(*dto.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentReplies indicates an expected call of GetCommentReplies.
func (mr *MockCommentUseCaseMockRecorder) GetCommentReplies(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentReplies", reflect.TypeOf((*MockCommentUseCase)(nil).GetCommentReplies), ctx, params)
}

// GetTopListComments mocks base method.
func (m *MockCommentUseCase) GetTopListComments(ctx context.Context, params dto.CommentRequest) (*dto.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopListComments", ctx, params)
	ret0, _ := ret[0].(*dto.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopListComments indicates an expected call of GetTopListComments.
func (mr *MockCommentUseCaseMockRecorder) GetTopListComments(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopListComments", reflect.TypeOf((*MockCommentUseCase)(nil).GetTopListComments), ctx, params)
}
