// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Comment struct {
	ID               string `json:"id"`
	PostID           int    `json:"postId"`
	ReplyToCommentID *int   `json:"replyToCommentId,omitempty"`
	UserID           int    `json:"userId"`
	Text             string `json:"text"`
}

type CommentRepliesRequest struct {
	PostID           int `json:"postId"`
	ReplyToCommentID int `json:"replyToCommentId"`
	Limit            int `json:"limit"`
	Offset           int `json:"offset"`
}

type CommentRequest struct {
	PostID int `json:"postId"`
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type CommentResponse struct {
	Len      int        `json:"len"`
	Comments []*Comment `json:"comments"`
}

type CreateCommentRequest struct {
	PostID           int    `json:"postId"`
	ReplyToCommentID *int   `json:"replyToCommentId,omitempty"`
	UserID           int    `json:"userId"`
	Text             string `json:"text"`
}

type CreatePostRequest struct {
	UserID          int    `json:"userId"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Mutation struct {
}

type Post struct {
	ID              string `json:"id"`
	UserID          int    `json:"userId"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type PostRequest struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type PostResponse struct {
	Len   int     `json:"len"`
	Posts []*Post `json:"posts"`
}

type Query struct {
}

type Subscription struct {
}
