package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"log"
	"strconv"

	"github.com/dubovayaRoshcha/posts-service/internal/usecase/dto"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, params CreatePostRequest) (*Post, error) {
	post, err := r.postUC.CreatePost(ctx, dto.PostDTO{
		UserID:          params.UserID,
		Title:           params.Title,
		Description:     params.Description,
		CommentsAllowed: params.CommentsAllowed,
	})
	if err != nil {
		log.Printf("CreatePost: %v", err)
		return nil, err
	}

	return &Post{
		ID:              strconv.Itoa(post.ID),
		UserID:          post.UserID,
		Title:           post.Title,
		Description:     post.Description,
		CommentsAllowed: post.CommentsAllowed,
	}, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, params CreateCommentRequest) (*Comment, error) {
	comment, err := r.commentUC.CreateComment(ctx, dto.CommentDTO{
		PostID:           params.PostID,
		ReplyToCommentID: params.ReplyToCommentID,
		UserID:           params.UserID,
		Text:             params.Text,
	})
	if err != nil {
		log.Printf("CreateComment: %v", err)
		return nil, err
	}

	return &Comment{
		ID:               strconv.Itoa(comment.ID),
		PostID:           comment.PostID,
		ReplyToCommentID: comment.ReplyToCommentID,
		UserID:           comment.UserID,
		Text:             comment.Text,
	}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, params PostRequest) (*PostResponse, error) {
	postsResp, err := r.postUC.GetListPosts(ctx, dto.PostRequest{
		Limit:  params.Limit,
		Offset: params.Offset,
	})
	if err != nil {
		log.Printf("Posts: %v", err)
		return nil, err
	}

	posts := make([]*Post, 0, len(postsResp.Posts))

	for _, post := range postsResp.Posts {
		posts = append(posts, &Post{
			ID:              strconv.Itoa(post.ID),
			UserID:          post.UserID,
			Title:           post.Title,
			Description:     post.Description,
			CommentsAllowed: post.CommentsAllowed,
		})
	}

	return &PostResponse{Len: postsResp.Len, Posts: posts}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*Post, error) {
	post, err := r.postUC.GetPostByID(ctx, id)
	if err != nil {
		log.Printf("Post: %v", err)
		return nil, err
	}

	return &Post{
		ID:              strconv.Itoa(post.ID),
		UserID:          post.UserID,
		Title:           post.Title,
		Description:     post.Description,
		CommentsAllowed: post.CommentsAllowed,
	}, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, params CommentRequest) (*CommentResponse, error) {
	commentsResp, err := r.commentUC.GetTopListComments(ctx, dto.CommentRequest{
		PostID: params.PostID,
		Limit:  params.Limit,
		Offset: params.Offset,
	})
	if err != nil {
		log.Printf("Comments: %v", err)
		return nil, err
	}

	comments := make([]*Comment, 0, len(commentsResp.Comments))

	for _, comment := range commentsResp.Comments {
		comments = append(comments, &Comment{
			ID:               strconv.Itoa(comment.ID),
			PostID:           comment.PostID,
			ReplyToCommentID: comment.ReplyToCommentID,
			UserID:           comment.UserID,
			Text:             comment.Text,
		})
	}

	return &CommentResponse{Len: commentsResp.Len, Comments: comments}, nil
}

// Replies is the resolver for the replies field.
func (r *queryResolver) Replies(ctx context.Context, params CommentRepliesRequest) (*CommentResponse, error) {
	commentsResp, err := r.commentUC.GetCommentReplies(ctx, dto.CommentRequest{
		PostID:           params.PostID,
		ReplyToCommentID: &params.ReplyToCommentID,
		Limit:            params.Limit,
		Offset:           params.Offset,
	})
	if err != nil {
		log.Printf("Replies: %v", err)
		return nil, err
	}

	comments := make([]*Comment, 0, len(commentsResp.Comments))

	for _, comment := range commentsResp.Comments {
		comments = append(comments, &Comment{
			ID:               strconv.Itoa(comment.ID),
			PostID:           comment.PostID,
			ReplyToCommentID: comment.ReplyToCommentID,
			UserID:           comment.UserID,
			Text:             comment.Text,
		})
	}

	return &CommentResponse{Len: commentsResp.Len, Comments: comments}, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int) (<-chan *Comment, error) {
	panic(fmt.Errorf("not implemented: CommentAdded - commentAdded"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
